# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  flake.modules.nixos.adam =
    {
      config,
      lib,
      ...
    }:

    {
      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/luks-37471d57-a31d-4bf1-b219-9992bafe7b64";
        fsType = "ext4";
      };

      boot.initrd.luks.devices."luks-37471d57-a31d-4bf1-b219-9992bafe7b64".device =
        "/dev/disk/by-uuid/37471d57-a31d-4bf1-b219-9992bafe7b64";

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/8E50-FCCA";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [
        { device = "/dev/mapper/luks-803851e9-7fa8-4367-a927-0bb76d0fe830"; }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
